workspace:
  base: /go
  path: src/github.com/patwie/pylint

pipeline:
  testing:
    image: golang:1.10.0
    commands:
      - go build server.go db.go config.go payload.go redis.go
      - go build worker.go db.go config.go payload.go redis.go
