version: "3"


services:
  web:
    image: golang:1.8
    restart: always
    environment:
      - PYLINT_CONFIGURATION=pylint-configuration.yml
    volumes:
      - .:/go/src/github.com/patwie/pylint
      - report-data:/data/reports
    working_dir: /go/src/github.com/patwie/pylint
    command: ./scripts/server_startup.sh
    links:
      - redis
    ports:
      - "8080:8080"

  worker:
    image: golang:1.8
    restart: always
    environment:
      - PYLINT_CONFIGURATION=pylint-configuration.yml
    volumes:
      - .:/go/src/github.com/patwie/pylint
      - ./keys:/keys
      - report-data:/data/reports
    working_dir: /go/src/github.com/patwie/pylint
    command: ./scripts/worker_startup.sh
    links:
      - redis

  redis:
    hostname: redis
    restart: always
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  report-data:
