version: "3"


services:
  web:
    image: golang:1.8
    volumes:
      - .:/go/src/pylint
      - report-data:/data/reports
    working_dir: /go/src/pylint
    command: go run server.go db.go config.go payload.go redis.go
    links:
      - pool:redis
    env_file:
      - .env
    ports:
      - "${PYLINTGO_PUBLICPORT}:4444"
  worker:
    image: golang:1.8
    volumes:
      - .:/go/src/pylint
      - ./keys:/keys
      - report-data:/data/reports
    working_dir: /go/src/pylint
    env_file:
      - .env
    command: ./worker_startup.sh
    links:
      - pool:redis
  shell:
    image: golang:1.8
    volumes:
      - .:/go/src/pylint
      - report-data:/data/reports
    working_dir: /go/src/pylint
    env_file:
      - .env
    command: bash
  pool:
    image: redis:alpine
  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=${PYLINTGO_DB_USER}
      - POSTGRES_PASSWORD=${PYLINTGO_DB_PASSWORD}
      - POSTGRES_DB=${PYLINTGO_DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  report-data:
  postgres-data: